### ISSUE TITLE
Processing issue

### ISSUE THREAD

**Issue by kanongil** [jeffjewiss/broccoli-postcss#236]
The `from` / `to` paths passed to `postcss` are relative. This causes filters that need to access other files in the tree, like `postcss-inline-svg`, to fail to find the correct files. Rather than finding it in the tree, it will search the source files instead. This means that any processing on these files are lost, or that it fails to find the file since it would be generated / renamed during tree processing.

I suspect it can be fixed by prepending `this.inputPath` / `this.outputPath` to the passed options.

**Comment by jeffjewiss** [comment]
Thanks for reporting this!

Do you have a current project where this isn't working correctly? If I put a potential fix in a branch, would you be able to test it against your project?

Thanks!

**Comment by kanongil** [comment]
Yes, and yes!

Though, I'll be on and off during the weekend.

**Comment by jeffjewiss** [comment]
Okay great, I’ll put something together and let you know. No worries, no rush!

**Comment by jeffjewiss** [comment]
Hi @kanongil, please give https://github.com/jeffjewiss/broccoli-postcss/tree/path-issue-fix a try when you have a chance. Thanks!

**Comment by jeffjewiss** [comment]
Hey @kanongil, just wanted to check in and see if you'll have a chance to try that branch with your project. Thanks!
