### ISSUE TITLE
Dest dir?

### ISSUE THREAD

**Issue by elranu** [jeffjewiss/broccoli-postcss#33]
Sorry I'm new with brocolli and also postcss

is there a way to set the destDir???

```
options.destDir = 'somoDir':
compileCSS('assets/styles/vendor/css', options);
```
Regards,
Mariano

**Comment by jeffjewiss** [comment]
Hi Mariano,

No worries, typically you set the destination directory in either your `Brocfile.js` or using broccoli-cli `broccoli build <destDir>`.

The broccoli postcss plugin acts as a filter and operates on any CSS files that are part of the tree/node you feed into Broccoli.

Here's an example [Brocfile.js](https://github.com/broccolijs/broccoli-sample-app/blob/master/Brocfile.js) and there's a bit more info on the [repo](https://github.com/broccolijs/broccoli).

I'm going to close this issue, but please reply if you have any further questions and I'll try to help out.
