### ISSUE TITLE
Support for nodejs 12.x?

### ISSUE THREAD

**Issue by mileslane** [jeffjewiss/broccoli-postcss#345]
Thank you for taking the time to open an issue!

For bug reports, please provide the version of `broccoli-postcss`, and list of postcss plugins you are using.

**Comment by jeffjewiss** [comment]
Hi, is there a specific error you're seeing with Node 12.x?

It should be supported by this library. I'll need a bit more information before I can help.

Thanks!

**Comment by nightire** [comment]
@jeffjewiss 

Because of the engine versions are specified, yarn throws this error when executing `yarn start`:

![image](https://user-images.githubusercontent.com/1104018/70962652-dbb36c00-20c0-11ea-8796-00f491c0896e.png)

Maybe we can set engine versions as ember.js does:

```json
{
  "engines": {
    "node": "8.* || >= 10.*"
  }
}
```

**Comment by jeffjewiss** [comment]
@nightire thanks for reporting this.

Are you using `broccoli-postcss` directly or through an Ember addon?

It looks like you're using v3.5.3, which is pretty old (May 2018). Are you able to update to `broccoli-postcss` v5.0.0? It supports any Node version after 8 for its engine. Updating to ember-cli-postcss v5.0.0 should also fix the issue.

**Comment by nightire** [comment]
@jeffjewiss According to your suggestion, I run `yarn why broccoli-postcss` and I found the older version is coming from a 3rd-party ember addon. Unfortunately, this addon seems like a lack of maintaining, so I add a `"resolution"` entry in my `package.json` to force yarn to install `v5.0.0` of broccoli-postcss. It works well, thank you.

**Comment by jeffjewiss** [comment]
@nightire glad to hear you were able to get this sorted out! Thanks for reporting back on the solution.
