### ISSUE TITLE
Fix example in the readme so the build won't fail

### ISSUE THREAD

**Issue by herrkris** [jeffjewiss/broccoli-postcss#60]
Thanks for your broccoli plugin. I was struggling to get it to work, because I'm knew to broccoli and just copied and pasted the example and the build was always failing.
Turns out it's no longer `cssnext` but `postcss-cssnext` :)

I'll provide a pull request for the fix in the readme!

**Comment by jeffjewiss** [comment]
Sorry this caused you trouble in setting up the plugin. Thanks for taking the time to find and submit the fix, I really appreciate it!
